version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test

  build_and_push_image:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Configure Heroku Container Registry credentials
          command: |
            echo -n "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
      - run:
          name: Build and push Docker image
          command: |
            docker build -t registry.heroku.com/$HEROKU_APP_NAME/web:${CIRCLE_SHA1} .
            docker push registry.heroku.com/$HEROKU_APP_NAME/web:${CIRCLE_SHA1}
      - run:
          name: Release to Heroku
          command: |
            heroku container:release web --app $HEROKU_APP_NAME

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - run_tests
      - build_and_push_image:
          requires:
            - run_tests
